accounts/urls.py
from django.urls import path
from . import views
from . import apis

from rest_framework_simplejwt.views import (
    TokenRefreshView, TokenVerifyView
)

app_name = 'accounts'

urlpatterns = [
    path('api/login/', apis.LoginAPI.as_view(), name='login'),
    path('api/logout/', apis.LogoutAPI.as_view(), name='logout'),
    path('api/refresh-token/', TokenRefreshView.as_view(), name='refresh_token'),
    path('api/verify-token/', TokenVerifyView.as_view(), name='verify_token'),

    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_view, name='logout_view'),
    path('home/', views.home_page, name='home_page'),
    path('register/', views.register_page, name='register_page'),
    path('confirm/', views.account_confirmation_page, name='account_confirmation_page'),
    path('password-reset/', views.forgot_password_page, name='forgot_password_page'),
    path('terms-and-policies/', views.terms_page, name='terms_page'),

    path('check-username/', views.check_username, name='check_username'),
    path('send-otp/', views.send_otp, name='send_otp'),
    path('confirm-otp/', views.confirm_otp, name='confirm_otp'),
    path('unique-key/', views.get_unique_key, name='get_unique_key'),
    path('reset-password/', views.reset_password, name='reset_password')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from django.utils import timezone

from trackmywork.utilities.model_fields import ConfidentialField


class UserManager(BaseUserManager):
    def create_user(self, username=None, password=None, email=None, is_active=True, terms=True):
        # Checking user entered valid data
        if not username:
            raise ValueError('User must have username')
        if not password:
            raise ValueError('User must have password')
        if not email:
            raise ValueError('User must have email')

        # Instantiate and save user data
        user = self.model(
            username=username, email=self.normalize_email(email), is_active=is_active,
            accept_terms_and_conditions = terms
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staff_user(self, username=None, password=None, email=None, is_active=True):
        user = self.create_user(
            username=username, email=email, password=password, is_active=is_active
        )
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, username=None, password=None, email=None, is_active=True):
        user = self.create_user(
            username=username, email=email, password=password, is_active=is_active
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=64, unique=True, db_index=True)
    email = models.EmailField(max_length=255, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    accept_terms_and_conditions = models.BooleanField(default=False)
    # password & last_login fields auto-injected by django BaseUser model

    class Meta:
        ordering = ['-created_at']
        get_latest_by = ['created_at']

    objects = UserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return f'{self.username} - {self.email}'

    @property
    def active(self):
        return self.is_active

    @property
    def staff(self):
        return self.is_staff

    @property
    def admin(self):
        return self.is_superuser

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def status(self):
        is_ok = getattr(self, 'accountstatus', True)
        if is_ok == True: return True
        else: return False

class AccountConfirmation(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    otp = models.CharField(max_length=6)
    confirmation_status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.confirmation_status:
            return f'{self.user.email} - Account Confirmed'
        return f'{self.user.email} - Account not Confirmed'

    def is_expired(self, hours=1):
        duration = timezone.now() - self.created_at
        return duration.seconds > hours*3600

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=64)
    mobile = ConfidentialField()
    photo = models.ImageField(upload_to='profile_pictures', null=True, blank=True)
    currently_worked_in = models.CharField(max_length=255)
    joined_date = models.DateField()

    def __str__(self):
        return f'{self.user.username} - {self.user.email}'


class Settings(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    remind_me = models.BooleanField(default=False)
    email_notification = models.BooleanField(default=True)
    profile_public_view = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username}'


class AccountStatus(models.Model):

    class InactiveReason(models.TextChoices):
        confirm = 'confirm', 'Account confirmation'
        purchase = 'purchase', 'Trial version expired'
        suspend = 'suspend', 'Account suspended by User'  

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    inactive_reason = models.CharField(max_length=255, choices=InactiveReason.choices)
    description = models.TextField()

    def __str__(self):
        return f'{self.user.username} - {self.inactive_reason}'


class UserSecret(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unique_key = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms

from .models import *


ValidationError = forms.ValidationError


class LoginForm(forms.Form):
	username = forms.CharField(max_length=64, required=True)
	password = forms.CharField(max_length=128, required=True)

class RegisterForm(forms.ModelForm):
	confirm_password = forms.CharField(max_length=128, required=True)
	class Meta:
		model = User
		fields = ['username', 'email', 'password', 'confirm_password', 'accept_terms_and_conditions']

	def clean(self):
		cleaned_data = super().clean()
		print(cleaned_data, 'form')

		if cleaned_data['accept_terms_and_conditions'] == False:
			self.add_error('You have to accept our terms and conditions to use this site', field='__all__')
			
		if cleaned_data['confirm_password'] != cleaned_data['password']:
			self.add_error(error='Password and Confirm password does not match', field='confirm_password')

		if not cleaned_data['username'].isidentifier():
			self.add_error(error='Username only allow _ as special character or must starts with alphabet', field='username')

		for char in cleaned_data['username']:
			if char.isupper():
				self.add_error(error='Username must be in lowercase', field='username')


class AccountConfirmationForm(forms.ModelForm):
	email = forms.EmailField(max_length=255, required=True)

	class Meta:
		model = AccountConfirmation
		fields = ['otp', 'email']

accounts/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMessage
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import (
    authenticate, login as django_login, logout as django_logout,
    get_user_model
)

from trackmywork.utilities.funcs import generate_otp
from .forms import *
from .selectors import get_user
from .services import create_account_confirmation, create_user, check_and_update_account_confirmation, create_user_secret

from trackmywork.config.base import KEEP_ME_SESSION_TIME, EMAIL_HOST_USER

User = get_user_model()

def login_page(request):
    z = False
    if request.user.is_authenticated: django_logout(request)
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        keep_me = True if request.POST.get('keep_me', None) == 'on' else False
        if z: print(keep_me)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = get_user(username)
            if isinstance(user, ObjectDoesNotExist):
                form.add_error(error='User does not exist', field='username')
            elif user:
                if not user.active:
                    form.add_error(error='Account Confirmation is required',field='__all__')
                if hasattr(user, 'accountstatus'):
                    form.add_error(error=user.accountstatus.description, field='__all__')
            
                if not form.errors:
                    valid_user = authenticate(username=user.username, password=password)
                    if valid_user:
                        if keep_me: request.session.set_expiry(KEEP_ME_SESSION_TIME)
                        django_login(request, valid_user)
                        return redirect('accounts:home_page')
                    else:
                        form.add_error(error='Password is incorrect', field='password')

    context = {'form': form}
    return render(request, 'accounts/login.html', context)

@login_required
def home_page(request):
    return render(request, 'accounts/home.html')


@login_required
def logout_view(request):
    django_logout(request)
    messages.info(request, 'Successfully logged out')
    return redirect('accounts:login_page')


def register_page(request):
    z = True
    if request.user.is_authenticated: django_logout(request)
    form = RegisterForm()
    context = {'created': False, 'form': form}
    if request.method == 'POST':
        requested_data = {
            'username': request.POST.get('username'),
            'password': request.POST.get('password'),
            'confirm_password': request.POST.get('confirm_password'),
            'email': request.POST.get('email'),
            'accept_terms_and_conditions': request.POST.get('terms', False)
        }
        form = RegisterForm(data=requested_data)
        if form.is_valid():
            form.cleaned_data.pop('confirm_password')
            form.cleaned_data['is_active'] = True
            if z: print('form valid', form.cleaned_data, 'view')
            user = create_user(**form.cleaned_data)
            otp = generate_otp()
            acc_conf = create_account_confirmation(user=user, otp=otp)
            if z: print(acc_conf.otp)
            us = create_user_secret(user)
            if z: print(us.unique_key)
            
            try:
                email = EmailMessage(subject='Account Confirmation OTP : Track My Work',
                body=f'''
                Hi {request.user.username}, your account confirmation otp is {otp}, expired in 60 minutes
                ''', from_email=EMAIL_HOST_USER, to=[user.email])
                email.send()
            except Exception as e:
                user.is_active = True
                user.save()
                if z: print(e) # [Errno 111] Connection refused
            form = RegisterForm()
            context.update({'form': form, 'created': True, 'key': us.unique_key})
        else:
            context.update({'created': False, 'form': form})
            if z: print('invalid form', form.errors, 'view')
    
    return render(request, 'accounts/register.html', context=context)


def check_username(request):
    z = False
    if request.method == 'POST' and request.is_ajax():
        user = get_user(request.POST['username'])
        if isinstance(user, ObjectDoesNotExist):
            status = True
            if z: print('hi')
        elif isinstance(user, User):
            status = False
            if z: print('hello')
        
        return JsonResponse(data={'success': status}, status=200)
    elif request.method == 'GET':
        return JsonResponse(data={'message': 'only allow post method'})


def account_confirmation_page(request):
    z = False
    form = AccountConfirmationForm()
    if request.method == 'POST':
        form = AccountConfirmationForm(request.POST)
        if form.is_valid():
            if z: print(form, 'valid')
            email = form.cleaned_data['email']
            otp = form.cleaned_data['otp']
            acc_conf = check_and_update_account_confirmation(email=email, otp=otp)
            if acc_conf == 'confirm':
                messages.info(request, 'Your account has been confirmed')
                return redirect('accounts:login_page')
            if acc_conf == 'not_found':
                form.add_error(error='email is does not match with user', field='email')
            if acc_conf == 'expired':
                form.add_error(error='OTP is expired, kindly click resend otp', field='__all__')
            if acc_conf == 'invalid':
                form.add_error(error='invalid otp try again', field='otp')
            if acc_conf == 'error':
                form.add_error(error='technical issue contact admin', field='__all__')
        else:
            if z: print(form.errors, 'invalid')

    context = {'form': form}
    return render(request, 'accounts/confirm.html', context)


def forgot_password_page(request):
    return render(request, 'accounts/forgot-password.html')


def send_otp(request):
    '''Password Reset Email OTP'''
    z = False
    if request.method == 'GET':
        return JsonResponse('only allow POST method')
    if request.method == 'POST':
        if z: print(request.POST)
        user = get_user(request.POST.get('username', ''))
        if isinstance(user, ObjectDoesNotExist):
            return JsonResponse(data={'success':False,'message': 'Username or Email does not exist'})
        
        ac_obj = AccountConfirmation.objects.get(user=user)
        ac_obj.otp = generate_otp()
        ac_obj.save()
        otp = ac_obj.otp
        print('OTP is sending ...', otp)
        try:
            email = EmailMessage(subject='Password Reset OTP : Track My Work',
            body=f'''
            Hi {request.user.username}, your password reset otp is {otp}, expired in 60 minutes
            ''', from_email=EMAIL_HOST_USER, to=[user.email])
            email.send(fail_silently=False)
            return JsonResponse(data={'success': False, 'message': 'Found Error in sending email, please choose "try another way"'})
        except Exception as e:
            if z: print(e)
        return JsonResponse(data={'success': True, 'message': 'password reset confirmation otp sent successfully to your email.'})


def confirm_otp(request):
    '''Password Reset Confirmation OTP'''
    if request.method == 'GET': return JsonResponse(data='only allow POST method', safe=False)
    if request.method == 'POST':
        otp = request.POST['otp']
        email = request.POST['email']
        try:
            ac_obj = AccountConfirmation.objects.get(user__email=email, otp=otp)
            return JsonResponse(data={'success': True, 'message': 'OTP Verified'})
        except AccountConfirmation.DoesNotExist:
            return JsonResponse(data={'success': False, 'message': 'Invalid OTP'})


def get_unique_key(request):
    z = False
    if request.method == 'GET':
        return JsonResponse('only allow POST method')
    if request.method == 'POST':
        status = False
        key = request.POST.get('key', '')
        email = request.POST.get('email', '')
        if z: print(key, email, 'key email')
        if key and email:
            try:
                u = UserSecret.objects.get(user__email=email, unique_key=key)
                if u: status = True
            except UserSecret.DoesNotExist:
                status = False
        return JsonResponse(data={'success': status})


def reset_password(request):
    if request.method == 'GET':
        return JsonResponse('only allow POST method')
    if request.method == 'POST':
        email = request.POST.get('email', '')
        key_or_otp = request.POST.get('key_or_otp', '')
        p1 = request.POST.get('password', '')
        p2 = request.POST.get('confirm_password', '')

        if p1 != p2:
            return JsonResponse(data={
                'status': 'error', 'message': 'Password and Confirm password does not match'})
        if len(key_or_otp) == 6:
            try:
                AccountConfirmation.objects.get(user__email=email, otp=key_or_otp)
            except AccountConfirmation.DoesNotExist:
                return JsonResponse(data={'status': 'error', 'message': 'Invalid OTP'})
        else:
            try:
                UserSecret.objects.get(user__email=email, unique_key=key_or_otp)
            except UserSecret.DoesNotExist:
                return JsonResponse(data={'status': 'error', 'message': 'Invalid Unique Key'})

        user = User.objects.get(email=email)
        user.set_password(p1)
        user.save()
        messages.info(request, 'password reset completed successfully')
        return JsonResponse(data={'status': 'success'})


def terms_page(request):

templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Home Page | TMW</title>
{% endblock %}

{% block body %}
<h1 class="p-5 text-green-600 text-xl">{{ request.user.username }}</h1>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% load icon %}
{% block title %}
<title>Register | Track My Work</title>
{% endblock %}

{% block body %}

{% if created %}
<div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true" id="key-modal">

	<div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>

	<div class="fixed z-10 inset-0 overflow-y-auto">
		<div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">

			<div
				class="relative bg-white text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-lg sm:w-full">
				<div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
					<div class="sm:flex sm:items-start">

						<div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
							<h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">Account Created
								Successfully
							</h3>
							<div class="mt-2">
								<p class="text-md text-gray-700 my-3">
									Your unique secret key for track my work is</p>
								<span
									class="bg-green-100 p-3 rounded-sm my-2 w-full flex justify-between items-center text-green-600">
									<i>{% icon "key" %}</i>
									<span id="user-unique-key">{{key}}</span>
									<i class="cursor-pointer" id="copy-key"
										onclick="copyToClipboard('#user-unique-key')">{% icon "copy" %}</i>
								</span>
								</p>
								<p class="text-red-600 text-sm my-2">Make sure that you copied before reload or perform
									any
									other
									actions.</p>
								<p class="text-sm text-slate-600">
									Do not share with anyone and store in secret place. It is useful and mandatory for
									all authorized actions made by you. This key ensures that you are the actual person
									to do the authorized requests.
								</p>
							</div>
						</div>
					</div>
				</div>
				<div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
					<button type="button" id="got-it-btn"
						class="w-full inline-flex justify-center border border-transparent shadow-sm px-4 py-2 bg-green-600 text-base font-medium text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 sm:ml-3 sm:w-auto sm:text-sm">Got
						it</button>

				</div>
			</div>
		</div>
	</div>
</div>
{% endif %}



<section>
	<div class="container my-6">
		<div class="border border-gray-100 p-8 my-12 max-w-2xl mx-auto">
			<form method="post" class="flex flex-col space-y-5" id="register-form">
				{% csrf_token %}
				<h3 class="text-sky-700 text-center text-2xl pb-8">Create A Free Account</h3>
				{% if form.non_field_errors %}
				{% for error in form.non_field_errors %}
				<p class="text-red-600 text-sm error">{{ error|escape }}</p>
				{% endfor %}
				{% endif %}
				<div class="flex flex-col space-y-3 w-full">
					<label for="id_username" class="text-slate-700">Username</label>
					<p class="text-slate-500 text-xs">only allows _ as special character and lower case letters, does
						not allow leading numbers</p>
					<input type="text" name="username" id="id_username" placeholder="Username" required
						class="border-slate-300 focus:border-sky-700" {% if form.username.value %}
						value="{{form.username.value}}" {% endif %} pattern="[a-z_]+[a-z0-9_]*" />
					<p class="text-red-600 text-sm hidden u_error" id="username-error"></p>
					{% if form.username.errors %}
					{% for error in form.username.errors %}
					<p class="text-red-600 text-sm u_error">{{ error|escape }}</p>
					{% endfor %}
					{% endif %}
				</div>
				<div class="flex flex-col space-y-3 w-full">
					<label for="id_email" class="text-slate-700">Email</label>
					<p class="text-slate-500 text-xs">please provide currently active mail address, confirmation link
						will be sent to that account</p>
					<input type="email" name="email" id="id_email" placeholder="Email Address" required
						class="border-slate-300 focus:border-sky-700" {% if form.email.value %}
						value="{{form.email.value}}" {% endif %} />
					<p class="text-red-600 text-sm hidden e_error" id="email-error"></p>
					{% if form.email.errors %}
					{% for error in form.email.errors %}
					<p class="text-red-600 text-sm e_error">{{ error|escape }}</p>
					{% endfor %}
					{% endif %}
				</div>
				<div class="flex flex-col space-y-3 w-full">
					<label for="id_password" class="text-slate-700">Password</label>
					<p class="text-slate-500 text-xs">to choose strong password</p>
					<ul class="text-slate-500 text-xs list-disc pl-4">
						<li id="p_1">Atleast one uppercase letter</li>
						<li id="p_2">Atleast one number</li>
						<li id="p_3">Atleast one special character</li>
						<li id="p_4">Minimum 6 characters long</li>
					</ul>
					<div id="password-strength-meter">
						<span class="status-bar border block p-1 relative">
							<i id="bar-percent" class="block h-full absolute left-0 top-0"></i>
						</span>
						<span class="block text-center text-xs text-slate-400" id="bar-text"></span>
					</div>
					<div class="flex">
						<input type="password" name="password" id="id_password" placeholder="Password" required
							class="border-slate-300 focus:border-sky-700 flex-1" {% if form.password.value %}
							value="{{form.password.value}}" {% endif %} />
						<span
							class="border py-2 px-3 flex bg-slate-100 justify-center items-center hover:cursor-pointer"
							id="password-visible-toggle">
							<i class="hidden">{% icon "eye-off" width="25" height="20" %}</i>
							<i>{% icon "eye" width="25" height="20" %}</i>
						</span>
					</div>
					{% if form.password.errors %}
					{% for error in form.password.errors %}
					<p class="text-red-600 text-sm p_error">{{ error|escape }}</p>
					{% endfor %}
					{% endif %}
				</div>
				<div class="flex flex-col space-y-3 w-full">
					<label for="id_confirm_password" class="text-slate-700">Confirm Password</label>
					<p class="text-slate-500 text-xs">re enter same password for confirm once again with awareness</p>
					<div class="flex">
						<input {% if form.confirm_password.value %} value="{{form.confirm_password.value}}" {% endif %}
							required type="password" name="confirm_password" id="id_confirm_password"
							placeholder="Re-Password" class="border-slate-300 focus:border-sky-700 flex-1" />
						<span
							class="border py-2 px-3 flex bg-slate-100 items-center justify-center hover:cursor-pointer"
							id="confirm-password-visible-toggle">
							<i class="hidden">{% icon "eye-off" width="25" height="20" %}</i>
							<i>{% icon "eye" width="25" height="20" %}</i>
						</span>
					</div>
					<p class="text-red-600 text-sm hidden cp_error" id="confirm-password-error"></p>
					{% if form.confirm_password.errors %}
					{% for error in form.confirm_password.errors %}
					<p class="text-red-600 text-sm cp_error">{{ error|escape }}</p>
					{% endfor %}
					{% endif %}
				</div>
				<div class="flex items-center">
					<div class="flex-1 flex items-center space-x-4">
						<input type="checkbox" class="outline-none" required id="id_terms" name="terms">
						<label for="id_terms">I accept
							<a href="{% url 'accounts:terms_page' %}" target="_blank"
								class="underline hover:text-sky-400 text-slate-700">terms and
								conditions</a>
						</label>
					</div>
				</div>
				<input type="submit" id="submit-button" value="Create"
					class="p-3 bg-green-700 hover:bg-green-800 text-white text-lg">
				<div class="flex items-center justify-between">
					<p class="text-slate-700">Already have an account ?
						<a href="{% url 'accounts:login_page' %}" class="text-sky-700 hover:text-sky-400 underline">Sign
							In</a>
					</p>
				</div>
			</form>
		</div>
	</div>
</section>

{% endblock %}

{% block script %}
<script>
	$('#id_username').focus()

	function containsSpecialChars(str) {
		const specialChars = /[ `!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/;
		return specialChars.test(str);
	}
	function containsNumber(str) {
		const numberChars = /[0-9]/;
		return numberChars.test(str);
	}
	function containsUppercaseChar(str) {
		const uppercaseChars = /[A-Z]/;
		return uppercaseChars.test(str);
	}
	function removeExistingClass(class_list, where) {
		class_list.forEach(function (klass) {
			if (where.hasClass(klass)) { where.removeClass(klass) }
		})
	}
	function checkAndSetPasswordsMatchError(p1, p2) {
		if (p1 && p2 && p1 !== p2) {
			$('.cp_error').each((k, p) => { $(p).empty() })
			$('#confirm-password-error').removeClass('hidden').html('Password and Confirm Password does not match');
		}
		else {
			$('#confirm-password-error').addClass('hidden').html('');
		}
	}

	// Username Input Change Trigger
	$('#id_username').change(function (event) {
		username_input = $(event.target);
		value = username_input.val();
		token = '{{ csrf_token }}';
		$.ajax({
			url: '{% url "accounts:check_username" %}',
			type: 'post',
			data: { username: value, 'csrfmiddlewaretoken': token },
			success: function (res) {
				if (res.success === true) {
					$('#username-error').addClass('hidden').html('')
				}
				else {
					$('#username-error').removeClass('hidden').html('Username already exists try something new !')
				}

			},
			error: function (err) {
				console.log(err)
			}
		})
	})
	$('#id_username').keyup(() => { $('#username-error').html('').addClass('hidden') })

	// Email Input Change Trigger
	$('#id_email').change(function (event) {
		console.log('works')
		let email_input = $(event.target);
		let value = email_input.val();
		let csrf_value = '{{ csrf_token }}'
		$.ajax({
			url: '{% url "accounts:check_username" %}',
			type: "post",
			data: { username: value, 'csrfmiddlewaretoken': csrf_value },
			success: function (res) {
				console.log(res)
				if (res.success === true) {
					$('#email-error').addClass('hidden').html('')
				}
				else {
					$('#email-error').removeClass('hidden').html('Email already exists')
				}
			},
			error: function (err) {
				console.log(err)
			}
		})
	})
	$('#id_email').keyup(() => { $('#email-error').html('').addClass('hidden') })

	// Password Input Key Up Trigger
	$('#id_password').keyup(function (event) {
		let password_input = $(event.target);
		let value = password_input.val();
		let count = 0

		if (containsUppercaseChar(value)) {
			count++;
			$('#p_1').addClass('line-through')
		}
		else { $('#p_1').removeClass('line-through') }

		if (containsNumber(value)) {
			count++;
			$('#p_2').addClass('line-through');
		}
		else { $('#p_2').removeClass('line-through'); }

		if (containsSpecialChars(value)) {
			count++;
			$('#p_3').addClass('line-through');
		}
		else { $('#p_3').removeClass('line-through'); }

		if (value.length >= 6) {
			count++;
			$('#p_4').addClass('line-through');
		}
		else { $('#p_4').removeClass('line-through') }

		removeExistingClass(
			['w-[25%]', 'w-[50%]', 'w-[75%]', 'w-[100%]',
				'bg-red-500', 'bg-yellow-500', 'bg-green-500'],
			$('#bar-percent')
		);
		if (count == 0) {
			$('#bar-text').html('')
		}
		else if (count == 1) {
			$('#bar-percent').addClass('bg-red-500 w-[25%]');
			$('#bar-text').html('Weak')
		}
		else if (count == 2) {
			$('#bar-percent').addClass('bg-red-500 w-[50%]');
			$('#bar-text').html('Average')
		}
		else if (count == 3) {
			$('#bar-percent').addClass('bg-yellow-500 w-[75%]');
			$('#bar-text').html('Normal')
		}
		else if (count == 4) {
			$('#bar-percent').addClass('bg-green-500 w-[100%]')
			$('#bar-text').html('Good')
		}
		checkAndSetPasswordsMatchError(value, $('#id_confirm_password').val());
	});

	// Confirm Password Input Key Up Trigger
	$('#id_confirm_password').keyup(function (event) {
		confirm_password_input = $(event.target);
		let cp_value = confirm_password_input.val();
		let p_value = $('#id_password').val();

		checkAndSetPasswordsMatchError(p_value, cp_value);
	})
	$('#password-visible-toggle').click(function () {
		$('#password-visible-toggle').find('i').each(function (k, image) {
			$(image).toggleClass('hidden')
		});
		existing_type = $('#id_password').prop('type')
		if (existing_type === 'password') { $('#id_password').prop('type', 'text'); }
		else { $('#id_password').prop('type', 'password'); }
	})
	$('#confirm-password-visible-toggle').click(function () {
		$('#confirm-password-visible-toggle').find('i').each(function (k, image) {
			$(image).toggleClass('hidden')
		});
		existing_type = $('#id_confirm_password').prop('type')
		if (existing_type == 'password') { $('#id_confirm_password').prop('type', 'text'); }
		else { $('#id_confirm_password').prop('type', 'password'); }
	})

	{% if created %}
	$('#got-it-btn').click(function () {
		$('#key-modal').remove();

		window.location.replace("{% url 'accounts:login_page' %}");
	})

	$('#copy-key').click(function () {
		$('#copy-key').html('copied')
	})


	{% endif %}
</script>
{% endblock %}