accounts/urls.py
from django.urls import path
from . import views
from . import apis

from rest_framework_simplejwt.views import (
    TokenRefreshView, TokenVerifyView
)

app_name = 'accounts'

urlpatterns = [
    path('api/login/', apis.LoginAPI.as_view(), name='login'),
    path('api/logout/', apis.LogoutAPI.as_view(), name='logout'),
    path('api/refresh-token/', TokenRefreshView.as_view(), name='refresh_token'),
    path('api/verify-token/', TokenVerifyView.as_view(), name='verify_token'),

    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_view, name='logout_view'),
    path('home/', views.home_page, name='home_page'),
    path('register/', views.register_page, name='register_page'),
    path('confirm/', views.account_confirmation_page, name='account_confirmation_page'),
    path('password-reset/', views.forgot_password_page, name='forgot_password_page'),
    path('terms-and-policies/', views.terms_page, name='terms_page'),

    path('check-username/', views.check_username, name='check_username'),
    path('send-otp/', views.send_otp, name='send_otp'),
    path('confirm-otp/', views.confirm_otp, name='confirm_otp'),
    path('unique-key/', views.get_unique_key, name='get_unique_key'),
    path('reset-password/', views.reset_password, name='reset_password')
]

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="{% static 'images/tmw.svg' %}" type="image/x-icon">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link
		href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
		rel="stylesheet">
	<style>
		html,
		body {
			font-family: 'Montserrat', 'ubuntu', sans-serif;
		}
	</style>
	{% tailwind_preload_css %}
	{% tailwind_css %}
	{% block head %} {% endblock %}
</head>

<body>
	{% include 'header.html' %}
	<main class="mx-[5%] sm:max-w-7xl sm:mx-auto">
		{% block body %} {% endblock %}
	</main>

	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

	<script>

		$('#user-button').click((e) => {
			$('#user-dropdown').toggleClass('hidden')
		})

		function toggleMenu() {
			$('#mobile-menu').toggleClass('hidden')
		}

		function copyToClipboard(element) {
			var $temp = $("<input>");
			$("body").append($temp);
			$temp.val($(element).text()).select();
			document.execCommand("copy");
			$temp.remove();
		}
	</script>
	{% block script %} {% endblock %}
</body>

</html>

templates/header.html
{% load static %}
{% load icon %}
<header class="border-b-2 border-gray-100 sticky top-0 z-99">
	<div class="relative bg-white">
		<div class="max-w-7xl mx-auto px-4 sm:px-6">
			<div class="flex justify-between sm:justify-start items-center py-3 md:justify-start md:space-x-10">
				<div class="flex justify-start lg:w-0 lg:flex-1">
					<a href="{% url 'index_page' %}" class="flex items-center">
						<img class="h-8 w-auto sm:h-10" src="{% static 'images/tmw.svg' %}" alt="">
						<span class="ml-4 text-green-700 text-2xl">Track My Work</span>
					</a>
				</div>
				<div class=" -my-2 md:hidden mx-auto mr-2">
					<button type="button" onclick="toggleMenu()"
						class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-green-500"
						aria-expanded="false">
						<span class="sr-only">Open menu</span>
						{% icon "menu" %}
					</button>
				</div>
				<nav class="hidden md:flex space-x-10">
					<a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900">
						Documentation
					</a>
					<a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900">
						About
					</a>
				</nav>
				<div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
					{% if request.user.is_authenticated %}
					<!-- <a href="{% url 'accounts:logout_view' %}" title="Sign out" id="logout-link1"
						class="whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900">
						{% icon "log-out" %}
					</a> -->
					{% else %}
					<a href="{% url 'accounts:login_page' %}"
						class="whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900"> Sign
						in
					</a>
					<a href="{% url 'accounts:register_page' %}"
						class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-1 border border-transparent shadow-sm text-base font-medium text-white bg-green-600 hover:bg-green-700">
						Sign up </a>
					{% endif %}
				</div>

				{% if request.user.is_authenticated %}
				<!-- This example requires Tailwind CSS v2.0+ -->
				<div class="relative inline-block text-left">
					<div class="flex justify-between items-center space-x-4">
						<span
							class="hidden sm:inline-block text-black text-xl font-semibold capitalize">{{request.user.username}}</span>
						<button type="button" id="user-button" aria-expanded="true" aria-haspopup="true"
							class="border p-2 rounded-full">
							{% icon 'user' %}
						</button>
					</div>

					<!--
				    Dropdown menu, show/hide based on menu state.
				
				    Entering: "transition ease-out duration-100"
				      From: "transform opacity-0 scale-95"
				      To: "transform opacity-100 scale-100"
				    Leaving: "transition ease-in duration-75"
				      From: "transform opacity-100 scale-100"
				      To: "transform opacity-0 scale-95"
				  -->
					<div id="user-dropdown"
						class="hidden origin-top-right absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none"
						role="menu" aria-orientation="vertical" aria-labelledby="user-button" tabindex="-1">
						<div class="py-1 sm:hidden" role="none">
							<span
								class="block text-blue-600 font-bold px-4 py-2 text-center">{{request.user.username}}</span>
						</div>
						<div class="py-1" role="none">
							<!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
							<a href="#" class="text-gray-700 px-4 py-2 text-sm flex items-center hover:bg-slate-200"
								role="menuitem" tabindex="-1" id="menu-item-4">
								{% icon 'user-check' class="mr-3" width="18" height="18" %} Profile</a>
							<a href="#" class="text-gray-700 px-4 py-2 text-sm flex items-center hover:bg-slate-200"
								role="menuitem" tabindex="-1" id="menu-item-4">
								{% icon 'briefcase' class="mr-3" width="18" height="18" %} Works</a>
						</div>

						<div class="py-1" role="none">
							<a href="#" class="text-gray-700 px-4 py-2 text-sm flex items-center hover:bg-slate-200"
								role="menuitem" tabindex="-1" id="menu-item-4">
								{% icon 'settings' class="mr-3" width="18" height="18" %} Settings</a>

						</div>
						<div class="py-1" role="none">
							<!-- <a href="#" class="text-gray-700 block px-4 py-2 text-sm" role="menuitem" tabindex="-1"
								id="menu-item-6">Delete</a> -->

							<a href="{% url 'accounts:logout_view' %}" title="Sign out" id="logout-link1"
								class="text-gray-700 px-4 py-2 text-sm flex items-center hover:bg-slate-200"
								role="menuitem" tabindex="-1">
								{% icon "log-out" class="mr-3" width="18" height="18" %} Sign Out
							</a>
						</div>
					</div>
				</div>
				{% endif %}
			</div>
		</div>


		<div id="mobile-menu"
			class="hidden absolute top-0 inset-x-0 p-2 transition transform origin-top-right md:hidden">
			<div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
				<div class="pt-5 pb-6 px-5">
					<div class="flex items-center justify-between">
						<div>
							<img class="h-8 w-auto" src="{% static 'images/tmw.svg' %}" alt="Workflow">
						</div>
						<div class="-mr-2">
							<button type="button" onclick="toggleMenu()"
								class="menu-toggle bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-green-500">
								<span class="sr-only">Close menu</span>
								<!-- Heroicon name: outline/x -->
								{% icon "x" %}
							</button>
						</div>
					</div>

				</div>
				<div class="py-6 px-5 space-y-6">
					<div class="grid grid-cols-2 gap-y-4 gap-x-8">
						<a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> Documentation </a>
						<a href="#" class="text-base font-medium text-gray-900 hover:text-gray-700"> About </a>
					</div>
					<div>
						{% if request.user.is_authenticated %}
						<a href="{% url 'accounts:logout_view' %}" id="logout-link2"
							class="w-full flex items-center justify-center px-4 py-2 border border-transparent shadow-sm text-base font-medium text-white bg-green-600 hover:bg-green-700">
							Sign out </a>
						{% else %}
						<a href="{% url 'accounts:register_page' %}"
							class="w-full flex items-center justify-center px-4 py-2 border border-transparent shadow-sm text-base font-medium text-white bg-green-600 hover:bg-green-700">
							Sign up </a>
						<p class="mt-6 text-center text-base font-medium text-gray-500">
							Existing customer?
							<a href="{% url 'accounts:login_page' %}" class="text-green-600 hover:text-green-500">
								Sign
								in </a>
						</p>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Home Page | TMW</title>
{% endblock %}

{% block body %}
<section class="flex items-center h-[60vh] justify-center">
	<h1 class="text-7xl text-sky-500">Welcome to Track my work</h1>
</section>
{% endblock %}